### PR TITLE
Refine add command

### LINKED ISSUE #34: As a user, I can add applicants

### PR DESCRIPTION
**Pull request by JasonCP14**
* `UniquePersonList` now rejects people with same `name`, `email`, `jobId` all together
* Update `add` command UG

Resolve #34

### CODE REVIEW

**Review by cliftonfelix — APPROVED** [review]
Other than UG, LGTM! We can still discuss and finalize UG later

**Comment by deeyonn** [comment]
Looks like it's failing codecov because coverage decreased. May need to implement more tests for the lines added.

**Review by maryjess — COMMENTED** [review]
Minor: I think it'll be better to refine the `CommandResult` in the `execute` method of AddCommand upon adding a person to show only his/her name, instead of the full details of the person.

**Review by maryjess — APPROVED** [review]
LGTM!

**Pull request merged**
